default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: db_development
  username: postgres
  password: postgres
  host: localhost

test:
  <<: *default
  database: db_test
  username: postgres
  password: postgres
  host: localhost

production:
  <<: *default
  database: db_production
  username: postgres
  password: postgres
  host: localhost
